### ISSUE TITLE
Warning: Trying to access array offset on value of type bool in Dpdpickup.php on line 164

### ISSUE THREAD

**Issue by IbrahimS2** [dpdconnect/magento2-shipping#97]
The cart is misbehaving due to this error "Warning: Trying to access array offset on value of type bool in `vendor/dpdconnect/magento2-shipping/Model/Carrier/Dpdpickup.php on line 164`"

We are using Magento 2.4.7-p1, PHP8.3

```
#0 /home/magento/vendor/dpdconnect/magento2-shipping/Model/Carrier/Dpdpickup.php(164): Magento\\Framework\\App\\ErrorHandler->handler()
#1 /home/magento/vendor/magento/module-shipping/Model/Shipping.php(335): DpdConnect\\Shipping\\Model\\Carrier\\Dpdpickup->collectRates()
#2 /home/magento/vendor/magento/module-shipping/Model/Shipping.php(244): Magento\\Shipping\\Model\\Shipping->collectCarrierRates()
#3 /home/magento/vendor/magento/module-quote/Model/Quote/Address.php(1090): Magento\\Shipping\\Model\\Shipping->collectRates()
#4 /home/magento/generated/code/Magento/Quote/Model/Quote/Address/Interceptor.php(239): Magento\\Quote\\Model\\Quote\\Address->requestShippingRates()
#5 /home/magento/vendor/magento/module-quote/Model/Quote/Address.php(1017): Magento\\Quote\\Model\\Quote\\Address\\Interceptor->requestShippingRates()
#6 /home/magento/generated/code/Magento/Quote/Model/Quote/Address/Interceptor.php(230): Magento\\Quote\\Model\\Quote\\Address->collectShippingRates()
#7 /home/magento/vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php(92): Magento\\Quote\\Model\\Quote\\Address\\Interceptor->collectShippingRates()
#8 /home/magento/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(261): Magento\\Quote\\Model\\Quote\\Address\\Total\\Shipping->collect()
#9 /home/magento/vendor/magento/module-quote/Model/ShippingMethodManagement.php(336): Magento\\Quote\\Model\\Quote\\TotalsCollector->collectAddressTotals()
#10 /home/magento/vendor/magento/module-quote/Model/ShippingMethodManagement.php(269): Magento\\Quote\\Model\\ShippingMethodManagement->getShippingMethods()
#11 /home/magento/vendor/magento/module-quote/Model/GuestCart/GuestShippingMethodManagement.php(103): Magento\\Quote\\Model\\ShippingMethodManagement->estimateByExtendedAddress()
#12 [internal function]: Magento\\Quote\\Model\\GuestCart\\GuestShippingMethodManagement->estimateByExtendedAddress()
#13 /home/magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#14 /home/magento/vendor/magento/module-webapi/Controller/Rest.php(201): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process()
#15 /home/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch()
#16 /home/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent()
#17 /home/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#18 /home/magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins()
#19 /home/magento/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch()
#20 /home/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\Http->launch()
#21 /home/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\App\\Http\\Interceptor->___callParent()
#22 /home/magento/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\\Framework\\App\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#23 /home/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\\ApplicationPerformanceMonitor\\Plugin\\ApplicationPerformanceMonitor->aroundLaunch()
#24 /home/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\App\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#25 /home/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\\Framework\\App\\Http\\Interceptor->___callPlugins()
#26 /home/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->launch()
#27 /home/magento/pub/index.php(30): Magento\\Framework\\App\\Bootstrap->run()
#28 {main}
```

**Comment by n1mbleee** [comment]
any update?
